### ISSUE TITLE
Failed to load plugin libgazebo_ros_velodyne_gpu_laser.so

### ISSUE THREAD

**Issue by Ellinier** [MorpheusPD/MarsSim#1]
Hello, when I run `roslaunch mars-sim world.launch`, I came across an error and some warnings.

![image](https://user-images.githubusercontent.com/19636011/85913069-24b05e00-b864-11ea-8bd3-0671eb40dee7.png)

Can anyone help to solve it?

Many thanks!

**Comment by RiccardoGiubilato** [comment]
Hi Ellinier, 
you might just want to download and build the `velodyne_gazebo_plugins` ROS package from this repository https://bitbucket.org/DataspeedInc/velodyne_simulator/src/master/
just clone in the source space of your catkin workspace and build :-)
